// Mock trip data for demonstration
// In production, this would come from an API

export const MOCK_TRIPS = [
  {
    id: '1',
    operator: {
      name: 'Vexere Bus',
      logo: '🚌',
      rating: 4.8,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '07:30',
    arrivalTime: '14:45',
    duration: '7h 15m',
    price: 350000,
    seatsLeft: 12,
    totalSeats: 34,
    busType: 'Giường nằm',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
  {
    id: '2',
    operator: {
      name: 'Sao Việt',
      logo: '⭐',
      rating: 4.7,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '09:00',
    arrivalTime: '16:30',
    duration: '7h 30m',
    price: 320000,
    seatsLeft: 8,
    totalSeats: 40,
    busType: 'Ghế ngồi',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
  {
    id: '3',
    operator: {
      name: 'Luxe Bus',
      logo: '✨',
      rating: 4.9,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '10:15',
    arrivalTime: '18:00',
    duration: '7h 45m',
    price: 450000,
    seatsLeft: 5,
    totalSeats: 20,
    busType: 'Limousine',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
  {
    id: '4',
    operator: {
      name: 'Vexere Bus',
      logo: '🚌',
      rating: 4.8,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '14:00',
    arrivalTime: '21:15',
    duration: '7h 15m',
    price: 380000,
    seatsLeft: 15,
    totalSeats: 34,
    busType: 'Giường nằm',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
  {
    id: '5',
    operator: {
      name: 'Sao Việt',
      logo: '⭐',
      rating: 4.7,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '16:30',
    arrivalTime: '23:45',
    duration: '7h 15m',
    price: 300000,
    seatsLeft: 20,
    totalSeats: 40,
    busType: 'Ghế ngồi',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
  {
    id: '6',
    operator: {
      name: 'Luxe Bus',
      logo: '✨',
      rating: 4.9,
    },
    from: 'Bến xe Miền Đông (TP.HCM)',
    to: 'Bến xe Đà Nẵng',
    fromCode: 'SGN',
    toCode: 'DN',
    departureTime: '22:00',
    arrivalTime: '05:15',
    duration: '7h 15m',
    price: 480000,
    seatsLeft: 3,
    totalSeats: 20,
    busType: 'Limousine',
    pickupPoint: 'Bến xe Miền Đông, 292 Đường Kinh Dương Vương, Q.6',
    dropoffPoint: 'Bến xe Đà Nẵng, 70 Hàng Hải',
  },
];

